# Analyze AIT Log v2 Attack Phases

In [1]:
import pandas as pd

from utils import analyze_phase

## Load MSA Data

In [2]:
dataset = "aitv2"
scenario = "fox"
data_dir = f"../data/interim/{dataset}/{scenario}/flows_labeled"
file_path = f"{data_dir}/all_flows_labeled.csv"

In [3]:
df = pd.read_csv(file_path)

In [4]:
df.head()

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto,label,sensor_host,start_time_dt,end_time_dt,phase
0,f1921,1.642205e+09,1.642205e+09,0.099298,10.35.35.206,60538,91.189.91.157,123,udp,ntp,...,76,1,76,-,17,NTP,intranet_server,2022-01-15 00:00:00.869369984,2022-01-15 00:00:00.968667984,0
1,f14196,1.642205e+09,1.642205e+09,0.098276,192.168.128.4,60538,91.189.91.157,123,udp,ntp,...,76,1,76,-,17,NTP,inet_firewall,2022-01-15 00:00:00.870096922,2022-01-15 00:00:00.968372822,0
2,f3334,1.642205e+09,1.642205e+09,0.053324,172.17.129.140,43702,10.35.33.111,445,tcp,gssapi,...,514,4,379,-,6,benign_share,cloud_share,2022-01-15 00:00:02.130912066,2022-01-15 00:00:02.184236050,0
3,f5126,1.642205e+09,1.642205e+09,0.051889,172.17.129.140,43702,10.35.33.111,445,tcp,gssapi,...,514,4,379,-,6,benign_share,internal_share,2022-01-15 00:00:02.131725073,2022-01-15 00:00:02.183614016,0
4,f3335,1.642205e+09,1.642205e+09,0.012432,172.17.129.140,43704,10.35.33.111,445,tcp,gssapi,...,514,4,379,-,6,benign_share,cloud_share,2022-01-15 00:00:02.226455927,2022-01-15 00:00:02.238888025,0

In [5]:
df.value_counts("phase")

phase
0    400024
2     56443
1     14678
4        61
3        28
Name: count, dtype: int64

## Per Phase Analysis

In [6]:
df_benign = df[df["phase"] == 0]
df_phase_1 = df[df["phase"] == 1]
df_phase_2 = df[df["phase"] == 2]
df_phase_3 = df[df["phase"] == 3]
df_phase_4 = df[df["phase"] == 4]

### Phase 1 - Data Exfiltration

In [7]:
phase_1_labels = df_phase_1["label"].value_counts()
print("Phase 1 Label Distribution:")
print(phase_1_labels)

Phase 1 Label Distribution:
label
data exfiltration    14678
Name: count, dtype: int64

In [8]:
analyze_phase(df_phase_1, "Phase 1")

Total Flows: 14678

 --- IP distribution ---

Source IPs (1):
src_ip
192.168.255.254    14678
Name: count, dtype: int64

Destination IPs (1):
dst_ip
192.168.130.77    14678
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (13109):
sport
6123     4
50163    4
65507    4
35669    4
41516    3
        ..
53576    1
58676    1
23005    1
38452    1
43646    1
Name: count, Length: 13109, dtype: int64

Destination Ports (1):
dport
53    14678
Name: count, dtype: int64

(src_ip
 192.168.255.254    14678
 Name: count, dtype: int64,
 dst_ip
 192.168.130.77    14678
 Name: count, dtype: int64,
 sport
 6123     4
 50163    4
 65507    4
 35669    4
 41516    3
         ..
 53576    1
 58676    1
 23005    1
 38452    1
 43646    1
 Name: count, Length: 13109, dtype: int64,
 dport
 53    14678
 Name: count, dtype: int64)

In [9]:
def analyze_origin_destination(df, phase_name):
    origins = df["local_orig"].value_counts()
    print(f"{phase_name} Origin Distribution:")
    print(origins)

    destinations = df["local_resp"].value_counts()
    print(f"{phase_name} Destination Distribution:")
    print(destinations)

In [10]:
analyze_origin_destination(df_phase_1, "Phase 1")

Phase 1 Origin Distribution:
local_orig
T    14678
Name: count, dtype: int64
Phase 1 Destination Distribution:
local_resp
T    14678
Name: count, dtype: int64

### Phase 2 Analysis - Scanning

In [11]:
print("Number of samples in Phase 2:", len(df_phase_2))

Number of samples in Phase 2: 56443

In [12]:
analyze_origin_destination(df_phase_2, "Phase 2")

Phase 2 Origin Distribution:
local_orig
T    56443
Name: count, dtype: int64
Phase 2 Destination Distribution:
local_resp
T    56434
F        9
Name: count, dtype: int64

In [13]:
analyze_phase(df_phase_2, "Phase 2")

Total Flows: 56443

 --- IP distribution ---

Source IPs (5):
src_ip
172.17.130.196     52306
192.168.130.77      4128
192.168.128.4          5
192.168.128.195        3
192.168.130.110        1
Name: count, dtype: int64

Destination IPs (8204):
dst_ip
10.35.35.206       10666
172.17.130.37       2812
192.168.128.4       2649
10.35.33.111        2488
172.17.129.140      2393
                   ...
192.168.129.212        2
10.35.35.118           2
192.168.128.170        2
10.35.32.1             1
172.17.128.63          1
Name: count, Length: 8204, dtype: int64

 --- Port distribution ---
Source Ports (13622):
sport
59174    17
59510    16
59944    16
51730    15
34510    15
         ..
41648     1
54762     1
39222     1
54742     1
37206     1
Name: count, Length: 13622, dtype: int64

Destination Ports (1413):
dport
443      24981
80       16526
587         45
993         21
25          20
         ...
40000        7
53535        7
60123        6
823          6
1212         6
Name: count, Length: 1413, dtype: int64

(src_ip
 172.17.130.196     52306
 192.168.130.77      4128
 192.168.128.4          5
 192.168.128.195        3
 192.168.130.110        1
 Name: count, dtype: int64,
 dst_ip
 10.35.35.206       10666
 172.17.130.37       2812
 192.168.128.4       2649
 10.35.33.111        2488
 172.17.129.140      2393
                    ...
 192.168.129.212        2
 10.35.35.118           2
 192.168.128.170        2
 10.35.32.1             1
 172.17.128.63          1
 Name: count, Length: 8204, dtype: int64,
 sport
 59174    17
 59510    16
 59944    16
 51730    15
 34510    15
          ..
 41648     1
 54762     1
 39222     1
 54742     1
 37206     1
 Name: count, Length: 13622, dtype: int64,
 dport
 443      24981
 80       16526
 587         45
 993         21
 25          20
          ...
 40000        7
 53535        7
 60123        6
 823          6
 1212         6
 Name: count, Length: 1413, dtype: int64)

In [14]:
df_phase_2.columns

Index(['flow_id', 'start_time', 'end_time', 'duration', 'src_ip', 'sport',
       'dst_ip', 'dport', 'proto', 'service', 'orig_bytes', 'resp_bytes',
       'conn_state', 'local_orig', 'local_resp', 'missed_bytes', 'history',
       'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
       'tunnel_parents', 'ip_proto', 'label', 'sensor_host', 'start_time_dt',
       'end_time_dt', 'phase'],
      dtype='object')

In [15]:
phase_2_labels = df_phase_2["label"].value_counts()
print("Phase 2 Label Distribution:")
print(phase_2_labels)

Phase 2 Label Distribution:
label
host_discover_local      32788
service_scan             13924
dirb_scan                 8259
dns_brute_force_start     1192
host_discover_dmz          152
wpscan                     128
Name: count, dtype: int64

In [16]:
phase_2_labels = df_phase_2["label"].unique()
print("Unique labels in Phase 2:", phase_2_labels)

Unique labels in Phase 2: ['dns_brute_force_start' 'host_discover_local' 'host_discover_dmz'
 'service_scan' 'wpscan' 'dirb_scan']

In [17]:
phase_2_protocols = df_phase_2["proto"].value_counts()
print("Phase 2 Protocol Distribution:")
print(phase_2_protocols)

Phase 2 Protocol Distribution:
proto
tcp    56443
Name: count, dtype: int64

In [18]:
phase_2_ports = df_phase_2["dport"].value_counts()
print("Phase 2 Destination Port Distribution:")
print(phase_2_ports)

Phase 2 Destination Port Distribution:
dport
443      24981
80       16526
587         45
993         21
25          20
         ...
40000        7
53535        7
60123        6
823          6
1212         6
Name: count, Length: 1413, dtype: int64

In [19]:
# Label = host discover local
curr_label = phase_2_labels[0]
print(f"Analyzing Phase 2 - {curr_label}")
df_host_discover_local = df_phase_2[df_phase_2["label"] == curr_label]
analyze_origin_destination(df_host_discover_local, f"Phase 2 - {curr_label}")
analyze_phase(df_host_discover_local, f"Phase 2 - {curr_label}")

Analyzing Phase 2 - dns_brute_force_start
Phase 2 - dns_brute_force_start Origin Distribution:
local_orig
T    1192
Name: count, dtype: int64
Phase 2 - dns_brute_force_start Destination Distribution:
local_resp
T    1192
Name: count, dtype: int64
Total Flows: 1192

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    1192
Name: count, dtype: int64

Destination IPs (1):
dst_ip
172.17.128.1    1192
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1149):
sport
56168    3
50802    2
57824    2
54470    2
60800    2
        ..
55468    1
35132    1
39152    1
39344    1
58562    1
Name: count, Length: 1149, dtype: int64

Destination Ports (1190):
dport
443      2
80       2
1027     1
8085     1
5968     1
        ..
1334     1
9643     1
2522     1
5999     1
49155    1
Name: count, Length: 1190, dtype: int64

(src_ip
 172.17.130.196    1192
 Name: count, dtype: int64,
 dst_ip
 172.17.128.1    1192
 Name: count, dtype: int64,
 sport
 56168    3
 50802    2
 57824    2
 54470    2
 60800    2
         ..
 55468    1
 35132    1
 39152    1
 39344    1
 58562    1
 Name: count, Length: 1149, dtype: int64,
 dport
 443      2
 80       2
 1027     1
 8085     1
 5968     1
         ..
 1334     1
 9643     1
 2522     1
 5999     1
 49155    1
 Name: count, Length: 1190, dtype: int64)

In [20]:
# Label = host discover local
df_host_discover_local = df_phase_2[df_phase_2["label"] == "host_discover_local"]
# analyze_origin_destination(df_host_discover_local, "Phase 2 - Host Discover Local")
analyze_phase(df_host_discover_local, "Phase 2 - Host Discover Local")

Total Flows: 32788

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    32788
Name: count, dtype: int64

Destination IPs (8192):
dst_ip
10.35.35.206    30
10.35.35.204     7
10.35.35.202     6
10.35.33.144     5
10.35.62.78      4
                ..
10.35.33.116     2
10.35.32.164     2
10.35.33.111     2
10.35.35.118     2
10.35.32.1       1
Name: count, Length: 8192, dtype: int64

 --- Port distribution ---
Source Ports (12752):
sport
57950    11
54154    11
57970     9
44204     9
52666     9
         ..
57546     1
50638     1
42880     1
60334     1
50218     1
Name: count, Length: 12752, dtype: int64

Destination Ports (2):
dport
80     16396
443    16392
Name: count, dtype: int64

(src_ip
 172.17.130.196    32788
 Name: count, dtype: int64,
 dst_ip
 10.35.35.206    30
 10.35.35.204     7
 10.35.35.202     6
 10.35.33.144     5
 10.35.62.78      4
                 ..
 10.35.33.116     2
 10.35.32.164     2
 10.35.33.111     2
 10.35.35.118     2
 10.35.32.1       1
 Name: count, Length: 8192, dtype: int64,
 sport
 57950    11
 54154    11
 57970     9
 44204     9
 52666     9
          ..
 57546     1
 50638     1
 42880     1
 60334     1
 50218     1
 Name: count, Length: 12752, dtype: int64,
 dport
 80     16396
 443    16392
 Name: count, dtype: int64)

In [21]:
def attack_frequency(df, phase_name):
    time_range = df["end_time"].max() - df["start_time"].min()
    attack_count = len(df)
    frequency = attack_count / time_range if time_range > 0 else 0
    print(f"{phase_name} Attack Frequency: {frequency:.4f} attacks per second")

In [22]:
print(f"Analyzing Phase 2:\n")
for curr_label in phase_2_labels:
    print(f"=== {curr_label} ===")
    df_curr_label = df_phase_2[df_phase_2["label"] == curr_label]
    # analyze_origin_destination(df_curr_label, f"Phase 2 - {curr_label}")
    analyze_phase(df_curr_label, f"Phase 2 - {curr_label}")
    # attack_frequency(df_curr_label, f"Phase 2 - {curr_label}")
    print()

Analyzing Phase 2:

=== dns_brute_force_start ===
Total Flows: 1192

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    1192
Name: count, dtype: int64

Destination IPs (1):
dst_ip
172.17.128.1    1192
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1149):
sport
56168    3
50802    2
57824    2
54470    2
60800    2
        ..
55468    1
35132    1
39152    1
39344    1
58562    1
Name: count, Length: 1149, dtype: int64

Destination Ports (1190):
dport
443      2
80       2
1027     1
8085     1
5968     1
        ..
1334     1
9643     1
2522     1
5999     1
49155    1
Name: count, Length: 1190, dtype: int64

=== host_discover_local ===
Total Flows: 32788

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    32788
Name: count, dtype: int64

Destination IPs (8192):
dst_ip
10.35.35.206    30
10.35.35.204     7
10.35.35.202     6
10.35.33.144     5
10.35.62.78      4
                ..
10.35.33.116     2
10.35.32.164     2
10.35.33.111     2
10.35.35.118     2
10.35.32.1       1
Name: count, Length: 8192, dtype: int64

 --- Port distribution ---
Source Ports (12752):
sport
57950    11
54154    11
57970     9
44204     9
52666     9
         ..
57546     1
50638     1
42880     1
60334     1
50218     1
Name: count, Length: 12752, dtype: int64

Destination Ports (2):
dport
80     16396
443    16392
Name: count, dtype: int64

=== host_discover_dmz ===
Total Flows: 152

 --- IP distribution ---

Source IPs (3):
src_ip
172.17.130.196     146
192.168.128.4        5
192.168.128.195      1
Name: count, dtype: int64

Destination IPs (10):
dst_ip
10.35.35.206       70
172.17.130.37      48
172.17.129.140     12
172.17.131.81       6
34.243.160.129      5
172.17.128.2        4
54.171.230.55       4
172.17.128.1        1
172.17.128.63       1
192.168.129.212     1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (75):
sport
45000    5
60590    4
47892    3
53792    2
49818    2
        ..
51756    2
45542    1
48564    1
46988    1
54260    1
Name: count, Length: 75, dtype: int64

Destination Ports (3):
dport
443    109
80      42
25       1
Name: count, dtype: int64

=== service_scan ===
Total Flows: 13924

 --- IP distribution ---

Source IPs (2):
src_ip
172.17.130.196    9796
192.168.130.77    4128
Name: count, dtype: int64

Destination IPs (7):
dst_ip
192.168.128.4      2649
172.17.130.37      2554
10.35.33.111       2486
10.35.35.206       2392
172.17.129.140     2381
192.168.128.195    1444
172.17.131.81        18
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (6469):
sport
56324    9
46520    8
53062    8
39856    8
59766    8
        ..
49130    1
53862    1
33648    1
45604    1
53410    1
Name: count, Length: 6469, dtype: int64

Destination Ports (1413):
dport
443      95
80       84
587      44
993      20
143      16
         ..
8222      6
5242      6
60123     6
9643      6
823       6
Name: count, Length: 1413, dtype: int64

=== wpscan ===
Total Flows: 128

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    128
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    128
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (64):
sport
55206    2
55208    2
55210    2
55212    2
55214    2
        ..
55324    2
55326    2
55328    2
55330    2
55332    2
Name: count, Length: 64, dtype: int64

Destination Ports (1):
dport
443    128
Name: count, dtype: int64

=== dirb_scan ===
Total Flows: 8259

 --- IP distribution ---

Source IPs (3):
src_ip
172.17.130.196     8256
192.168.128.195       2
192.168.130.110       1
Name: count, dtype: int64

Destination IPs (4):
dst_ip
10.35.35.206       8046
172.17.130.37       210
192.168.128.170       2
192.168.129.212       1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (4129):
sport
59976    4
55606    3
60704    2
60700    2
60698    2
        ..
58020    2
58018    2
58034    2
36672    1
54418    1
Name: count, Length: 4129, dtype: int64

Destination Ports (3):
dport
443    8255
25        2
80        2
Name: count, dtype: int64

### Phase 3 Analysis - Exploitation

In [23]:
phase_3_labels = df_phase_3["label"].unique()
print("Unique labels in Phase 3:", phase_3_labels)

Unique labels in Phase 3: ['upload_rce_shell' 'check_user_id' 'check_netstat_t' 'read_resolv'
 'check_network_config' 'check_ps_a' 'check_release' 'read_group'
 'read_passwd' 'check_date' 'list_web_dir' 'check_wp_config'
 'dump_wp_users' 'read_profile']

In [24]:
for curr_label in phase_3_labels:
    print(f"Analyzing Phase 3 - {curr_label}")
    df_curr_label = df_phase_3[df_phase_3["label"] == curr_label]
    # analyze_origin_destination(df_curr_label, f"Phase 3 - {curr_label}")
    analyze_phase(df_curr_label, f"Phase 3 - {curr_label}")
    attack_frequency(df_curr_label, f"Phase 3 - {curr_label}")
    print(len(df_curr_label))
    print()

Analyzing Phase 3 - upload_rce_shell
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35148    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - upload_rce_shell Attack Frequency: 0.4971 attacks per second
2

Analyzing Phase 3 - check_user_id
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35150    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_user_id Attack Frequency: 4.6372 attacks per second
2

Analyzing Phase 3 - check_netstat_t
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35152    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_netstat_t Attack Frequency: 6.6336 attacks per second
2

Analyzing Phase 3 - read_resolv
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35154    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - read_resolv Attack Frequency: 14.3710 attacks per second
2

Analyzing Phase 3 - check_network_config
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35156    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_network_config Attack Frequency: 6.2521 attacks per second
2

Analyzing Phase 3 - check_ps_a
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35158    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_ps_a Attack Frequency: 5.6442 attacks per second
2

Analyzing Phase 3 - check_release
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35160    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_release Attack Frequency: 4.7852 attacks per second
2

Analyzing Phase 3 - read_group
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35162    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - read_group Attack Frequency: 18.8990 attacks per second
2

Analyzing Phase 3 - read_passwd
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35164    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - read_passwd Attack Frequency: 17.8306 attacks per second
2

Analyzing Phase 3 - check_date
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35166    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_date Attack Frequency: 18.6795 attacks per second
2

Analyzing Phase 3 - list_web_dir
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35168    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - list_web_dir Attack Frequency: 4.4669 attacks per second
2

Analyzing Phase 3 - check_wp_config
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35170    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - check_wp_config Attack Frequency: 19.1210 attacks per second
2

Analyzing Phase 3 - dump_wp_users
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35172    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - dump_wp_users Attack Frequency: 6.1825 attacks per second
2

Analyzing Phase 3 - read_profile
Total Flows: 2

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    2
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
35174    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    2
Name: count, dtype: int64
Phase 3 - read_profile Attack Frequency: 18.0672 attacks per second
2

In [25]:
analyze_origin_destination(df_phase_3, "Phase 3")

Phase 3 Origin Distribution:
local_orig
T    28
Name: count, dtype: int64
Phase 3 Destination Distribution:
local_resp
T    28
Name: count, dtype: int64

In [26]:
analyze_phase(df_phase_3, "Phase 3")

Total Flows: 28

 --- IP distribution ---

Source IPs (1):
src_ip
172.17.130.196    28
Name: count, dtype: int64

Destination IPs (1):
dst_ip
10.35.35.206    28
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (14):
sport
35148    2
35150    2
35152    2
35154    2
35156    2
35158    2
35160    2
35162    2
35164    2
35166    2
35168    2
35170    2
35172    2
35174    2
Name: count, dtype: int64

Destination Ports (1):
dport
443    28
Name: count, dtype: int64

(src_ip
 172.17.130.196    28
 Name: count, dtype: int64,
 dst_ip
 10.35.35.206    28
 Name: count, dtype: int64,
 sport
 35148    2
 35150    2
 35152    2
 35154    2
 35156    2
 35158    2
 35160    2
 35162    2
 35164    2
 35166    2
 35168    2
 35170    2
 35172    2
 35174    2
 Name: count, dtype: int64,
 dport
 443    28
 Name: count, dtype: int64)

### Phase 4 Analysis - Cracking

In [27]:
analyze_origin_destination(df_phase_4, "Phase 4")

Phase 4 Origin Distribution:
local_orig
T    61
Name: count, dtype: int64
Phase 4 Destination Distribution:
local_resp
T    60
F     1
Name: count, dtype: int64

In [28]:
analyze_phase(df_phase_4, "Phase 4")

Total Flows: 61

 --- IP distribution ---

Source IPs (3):
src_ip
172.17.130.196    56
192.168.128.4      4
10.35.35.206       1
Name: count, dtype: int64

Destination IPs (5):
dst_ip
172.17.130.37      34
10.35.35.206       22
192.168.130.77      3
151.101.14.109      1
192.168.255.254     1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (31):
sport
55754    3
36406    2
35176    2
36408    2
36410    2
35178    2
51940    2
35180    2
36412    2
35182    2
59296    2
36414    2
36416    2
36418    2
36420    2
36422    2
36424    2
36426    2
36428    2
36430    2
36432    2
36434    2
36436    2
50330    2
50328    2
50334    2
50332    2
50336    2
50338    2
51972    1
45119    1
Name: count, dtype: int64

Destination Ports (3):
dport
443    43
80     17
53      1
Name: count, dtype: int64

(src_ip
 172.17.130.196    56
 192.168.128.4      4
 10.35.35.206       1
 Name: count, dtype: int64,
 dst_ip
 172.17.130.37      34
 10.35.35.206       22
 192.168.130.77      3
 151.101.14.109      1
 192.168.255.254     1
 Name: count, dtype: int64,
 sport
 55754    3
 36406    2
 35176    2
 36408    2
 36410    2
 35178    2
 51940    2
 35180    2
 36412    2
 35182    2
 59296    2
 36414    2
 36416    2
 36418    2
 36420    2
 36422    2
 36424    2
 36426    2
 36428    2
 36430    2
 36432    2
 36434    2
 36436    2
 50330    2
 50328    2
 50334    2
 50332    2
 50336    2
 50338    2
 51972    1
 45119    1
 Name: count, dtype: int64,
 dport
 443    43
 80     17
 53      1
 Name: count, dtype: int64)

In [29]:
df_phase_4_protocols = df_phase_4["proto"].value_counts()
print("Phase 4 Protocol Distribution:")
print(df_phase_4_protocols)

Phase 4 Protocol Distribution:
proto
tcp    61
Name: count, dtype: int64

In [30]:
analyze_origin_destination(df_benign, "Benign")

Benign Origin Distribution:
local_orig
T    400021
F         3
Name: count, dtype: int64
Benign Destination Distribution:
local_resp
T    337453
F     62571
Name: count, dtype: int64

In [31]:
analyze_origin_destination(df, "All Phases")

All Phases Origin Distribution:
local_orig
T    471231
F         3
Name: count, dtype: int64
All Phases Destination Distribution:
local_resp
T    408653
F     62581
Name: count, dtype: int64

In [32]:
phase4_ips = set(df_phase_4["src_ip"]).union(set(df_phase_4["dst_ip"]))
print("Unique IPs in Phase 4:", len(phase4_ips))
print(phase4_ips)

Unique IPs in Phase 4: 7
{'10.35.35.206', '192.168.130.77', '192.168.255.254', '172.17.130.37', '151.101.14.109', '172.17.130.196', '192.168.128.4'}

In [33]:
df_phase_4[df_phase_4["dst_ip"] == "10.35.35.206"]
# {'172.17.130.196', '172.17.130.37', '192.168.255.254', '10.35.35.206', '192.168.128.4', '151.101.14.109', '192.168.130.77'}

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto,label,sensor_host,start_time_dt,end_time_dt,phase
384659,f78497,1.642510e+09,1.642510e+09,32.502218,172.17.130.196,35176,10.35.35.206,443,tcp,ssl,...,7646,425,519402,-,6,online_cracking,vpn,2022-01-18 12:38:29.550966024,2022-01-18 12:39:02.053184032,4
384660,f17233,1.642510e+09,1.642510e+09,32.501220,172.17.130.196,35176,10.35.35.206,443,tcp,ssl,...,7646,433,529265,-,6,online_cracking,intranet_server,2022-01-18 12:38:29.551500082,2022-01-18 12:39:02.052720070,4
384704,f78499,1.642510e+09,1.642510e+09,1.099385,172.17.130.196,35178,10.35.35.206,443,tcp,ssl,...,10430,405,492169,-,6,online_cracking,vpn,2022-01-18 12:39:03.249042988,2022-01-18 12:39:04.348428011,4
384705,f17234,1.642510e+09,1.642510e+09,1.098563,172.17.130.196,35178,10.35.35.206,443,tcp,ssl,...,10430,436,530292,-,6,online_cracking,intranet_server,2022-01-18 12:39:03.249373913,2022-01-18 12:39:04.347936869,4
384709,f78502,1.642510e+09,1.642510e+09,2.725528,172.17.130.196,35180,10.35.35.206,443,tcp,ssl,...,10814,430,524001,-,6,online_cracking,vpn,2022-01-18 12:39:06.616677999,2022-01-18 12:39:09.342206001,4
384710,f17237,1.642510e+09,1.642510e+09,2.724900,172.17.130.196,35180,10.35.35.206,443,tcp,ssl,...,10814,434,529317,-,6,online_cracking,intranet_server,2022-01-18 12:39:06.616926908,2022-01-18 12:39:09.341826916,4
384724,f78528,1.642510e+09,1.642510e+09,0.091874,172.17.130.196,35182,10.35.35.206,443,tcp,ssl,...,8838,382,463247,-,6,online_cracking,vpn,2022-01-18 12:39:11.009594917,2022-01-18 12:39:11.101468801,4
384725,f17245,1.642510e+09,1.642510e+09,0.091646,172.17.130.196,35182,10.35.35.206,443,tcp,ssl,...,8838,402,489827,-,6,online_cracking,intranet_server,2022-01-18 12:39:11.009860992,2022-01-18 12:39:11.101506948,4
384741,f78507,1.642510e+09,1.642510e+09,96.252340,172.17.130.196,59296,10.35.35.206,80,tcp,http,...,1163,10,6644,-,6,online_cracking,vpn,2022-01-18 12:39:45.911967993,2022-01-18 12:41:22.164308071,4
384742,f17242,1.642510e+09,1.642510e+09,96.250871,172.17.130.196,59296,10.35.35.206,80,tcp,http,...,1163,10,6644,-,6,online_cracking,intranet_server,2022-01-18 12:39:45.912630081,2022-01-18 12:41:22.163501024,4
386316,f17321,1.642512e+09,1.642512e+09,5.486391,172.17.130.196,50328,10.35.35.206,80,tcp,http,...,2619,38,42147,-,6,online_cracking,intranet_server,2022-01-18 13:13:28.984114885,2022-01-18 13:13:34.470505953,4
386319,f78865,1.642512e+09,1.642512e+09,5.486757,172.17.130.196,50328,10.35.35.206,80,tcp,http,...,2619,35,38160,-,6,online_cracking,vpn,2022-01-18 13:13:28.990955114,2022-01-18 13:13:34.477712154,4
386324,f17318,1.642512e+09,1.642512e+09,5.026922,172.17.130.196,50330,10.35.35.206,80,tcp,http,...,805,9,5742,-,6,online_cracking,intranet_server,2022-01-18 13:13:29.423938036,2022-01-18 13:13:34.450860023,4
386325,f17319,1.642512e+09,1.642512e+09,5.026916,172.17.130.196,50332,10.35.35.206,80,tcp,http,...,1068,7,2960,-,6,online_cracking,intranet_server,2022-01-18 13:13:29.423993111,2022-01-18 13:13:34.450909138,4
386326,f17320,1.642512e+09,1.642512e+09,5.030393,172.17.130.196,50334,10.35.35.206,80,tcp,http,...,1071,14,12336,-,6,online_cracking,intranet_server,2022-01-18 13:13:29.424012899,2022-01-18 13:13:34.454405785,4
386327,f17317,1.642512e+09,1.642512e+09,5.023209,172.17.130.196,50336,10.35.35.206,80,tcp,http,...,758,8,4929,-,6,online_cracking,intranet_server,2022-01-18 13:13:29.424031019,2022-01-18 13:13:34.447240114,4
386328,f17322,1.642512e+09,1.642512e+09,6.782000,172.17.130.196,50338,10.35.35.206,80,tcp,http,...,1833,30,33210,-,6,online_cracking,intranet_server,2022-01-18 13:13:29.424189091,2022-01-18 13:13:36.206189156,4
386329,f78862,1.642512e+09,1.642512e+09,5.027160,172.17.130.196,50330,10.35.35.206,80,tcp,http,...,805,7,3084,-,6,online_cracking,vpn,2022-01-18 13:13:29.430852890,2022-01-18 13:13:34.458012819,4
386330,f78863,1.642512e+09,1.642512e+09,5.027193,172.17.130.196,50332,10.35.35.206,80,tcp,http,...,1068,7,2960,-,6,online_cracking,vpn,2022-01-18 13:13:29.430917025,2022-01-18 13:13:34.458110094,4
386331,f78864,1.642512e+09,1.642512e+09,5.030587,172.17.130.196,50334,10.35.35.206,80,tcp,http,...,1071,14,12336,-,6,online_cracking,vpn,2022-01-18 13:13:29.430982113,2022-01-18 13:13:34.461569071,4
386332,f78861,1.642512e+09,1.642512e+09,5.023334,172.17.130.196,50336,10.35.35.206,80,tcp,http,...,758,8,4929,-,6,online_cracking,vpn,2022-01-18 13:13:29.431026936,2022-01-18 13:13:34.454360962,4
386333,f78872,1.642512e+09,1.642512e+09,6.782242,172.17.130.196,50338,10.35.35.206,80,tcp,http,...,1833,30,33210,-,6,online_cracking,vpn,2022-01-18 13:13:29.431076050,2022-01-18 13:13:36.213318110,4

In [34]:
df_phase_4[df_phase_4["src_ip"] == "10.35.35.206"]

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto,label,sensor_host,start_time_dt,end_time_dt,phase
384711,f17236,1.642510e+09,1.642510e+09,2.582308,10.35.35.206,55754,192.168.130.77,80,tcp,http,...,354020,189,177269,-,6,online_cracking,intranet_server,2022-01-18 12:39:06.746751070,2022-01-18 12:39:09.329059124,4

In [35]:
def get_phase_ips(df, phase):
    print(f"=== Analyzing Phase {phase} IPs ===")
    phase_ips = set(df["src_ip"].unique()) | set(df["dst_ip"].unique())
    phase_src_ips = set(df["src_ip"].unique())
    phase_dst_ips = set(df["dst_ip"].unique())

    print(f"Unique IPs in Phase {phase}:", phase_ips)
    print(f"Unique Source IPs in Phase {phase}:", phase_src_ips)
    print(f"Unique Destination IPs in Phase {phase}:", phase_dst_ips)
    print()

    return phase_ips, phase_src_ips, phase_dst_ips

In [36]:
phase1_ips, phase1_src_ips, phase1_dst_ips = get_phase_ips(df_phase_1, 1)
phase2_ips, phase2_src_ips, phase2_dst_ips = get_phase_ips(df_phase_2, 2)
phase3_ips, phase3_src_ips, phase3_dst_ips = get_phase_ips(df_phase_3, 3)
phase4_ips, phase4_src_ips, phase4_dst_ips = get_phase_ips(df_phase_4, 4)

=== Analyzing Phase 1 IPs ===
Unique IPs in Phase 1: {'192.168.130.77', '192.168.255.254'}
Unique Source IPs in Phase 1: {'192.168.255.254'}
Unique Destination IPs in Phase 1: {'192.168.130.77'}

=== Analyzing Phase 2 IPs ===

Unique IPs in Phase 2: {'10.35.34.130', '10.35.56.113', '10.35.42.208', '10.35.32.108', '10.35.63.22', '10.35.59.146', '10.35.60.86', '10.35.48.6', '10.35.59.55', '10.35.36.141', '10.35.54.22', '10.35.59.102', '10.35.37.88', '10.35.52.99', '10.35.45.92', '10.35.46.112', '10.35.53.161', '10.35.34.21', '10.35.44.177', '10.35.56.62', '10.35.41.239', '10.35.51.57', '10.35.55.97', '10.35.45.179', '10.35.44.101', '10.35.37.246', '10.35.37.185', '10.35.62.53', '10.35.42.125', '10.35.54.58', '10.35.35.113', '10.35.43.192', '10.35.40.110', '10.35.49.168', '10.35.39.148', '10.35.61.204', '10.35.53.68', '192.168.128.195', '10.35.48.2', '10.35.50.98', '10.35.39.187', '10.35.46.23', '10.35.61.169', '10.35.43.25', '10.35.50.248', '10.35.36.120', '10.35.41.172', '10.35.56.175', '10.35.58.100', '10.35.32.101', '10.35.56.121', '10.35.63.197', '10.35.63.48', '10.35.59.59', '10.35.38.214', '10.35.60.151', '10.35.63.201', '10.35.55.195', '10.35.46.34', '10.35.50.164', '10.35.63.238', '10.35.52.35', '10.35.58.146', '10.35.47.24', '10.35.60.170', '10.35.55.166', '10.35.47.137', '10.35.57.120', '10.35.60.193', '10.35.59.98', '10.35.41.59', '10.35.58.237', '10.35.32.2', '10.35.52.17', '10.35.49.30', '10.35.34.98', '10.35.34.84', '10.35.49.254', '10.35.50.254', '10.35.39.88', '10.35.37.118', '10.35.54.122', '10.35.42.162', '10.35.49.216', '10.35.51.95', '10.35.38.199', '10.35.32.49', '10.35.36.235', '10.35.58.204', '10.35.48.83', '10.35.40.151', '10.35.55.40', '10.35.46.4', '10.35.54.106', '10.35.34.12', '10.35.44.39', '10.35.38.210', '10.35.54.107', '10.35.36.79', '10.35.39.252', '10.35.58.187', '10.35.49.101', '10.35.45.214', '10.35.34.244', '10.35.62.115', '10.35.39.150', '10.35.63.193', '10.35.63.15', '10.35.42.228', '10.35.40.240', '10.35.42.223', '10.35.44.66', '10.35.55.198', '10.35.54.224', '10.35.36.227', '10.35.54.82', '10.35.44.215', '10.35.63.132', '10.35.43.195', '10.35.52.240', '10.35.63.189', '10.35.43.245', '10.35.58.53', '10.35.50.203', '10.35.45.151', '10.35.52.211', '10.35.57.17', '10.35.54.141', '10.35.51.250', '10.35.53.153', '10.35.55.55', '10.35.36.57', '10.35.49.187', '10.35.60.202', '10.35.56.63', '10.35.32.91', '10.35.56.10', '10.35.38.52', '10.35.39.23', '10.35.37.133', '10.35.40.219', '10.35.52.32', '10.35.63.145', '10.35.47.38', '10.35.54.162', '10.35.43.72', '10.35.36.210', '10.35.34.46', '10.35.37.186', '10.35.46.195', '10.35.40.216', '10.35.34.110', '10.35.48.248', '10.35.51.219', '10.35.58.81', '10.35.57.169', '10.35.55.225', '10.35.48.153', '10.35.33.70', '10.35.55.147', '10.35.63.54', '10.35.55.208', '10.35.43.27', '10.35.56.38', '10.35.37.125', '10.35.41.57', '10.35.41.68', '10.35.45.146', '10.35.36.85', '10.35.50.41', '10.35.61.119', '10.35.50.23', '10.35.55.203', '10.35.38.229', '10.35.63.2', '10.35.37.91', '10.35.44.41', '10.35.55.212', '10.35.63.113', '10.35.41.217', '10.35.59.106', '10.35.36.195', '10.35.63.211', '10.35.56.82', '10.35.62.169', '10.35.48.90', '10.35.45.160', '10.35.57.22', '10.35.45.163', '10.35.63.131', '10.35.55.207', '10.35.51.208', '10.35.51.248', '10.35.61.194', '10.35.63.46', '10.35.40.242', '10.35.58.209', '10.35.39.172', '10.35.46.26', '10.35.38.79', '10.35.37.101', '10.35.46.152', '10.35.62.175', '10.35.50.227', '10.35.41.139', '10.35.58.173', '10.35.46.89', '10.35.48.63', '10.35.48.255', '10.35.38.164', '10.35.43.58', '10.35.35.126', '10.35.48.37', '10.35.63.24', '10.35.38.3', '10.35.56.157', '10.35.43.216', '10.35.58.32', '10.35.54.199', '10.35.59.87', '10.35.38.86', '10.35.45.197', '10.35.51.221', '10.35.53.146', '10.35.34.174', '10.35.33.69', '10.35.48.174', '10.35.49.79', '10.35.36.41', '10.35.40.213', '10.35.59.52', '10.35.55.1', '10.35.44.134', '10.35.38.202', '10.35.63.52', '10.35.40.192', '10.35.61.199', '10.35.32.119', '10.35.38.126', '10.35.54.155', '10.35.50.105', '10.35.58.247', '10.35.38.15', '10.35.34.56', '10.35.55.92', '10.35.38.221', '10.35.43.96', '10.35.61.74', '10.35.62.77', '10.35.62.106', '10.35.59.237', '10.35.45.86', '10.35.38.131', '10.35.54.253', '10.35.33.254', '10.35.37.72', '10.35.52.39', '10.35.36.255', '10.35.54.99', '10.35.57.33', '10.35.56.124', '10.35.35.15', '10.35.46.200', '10.35.41.69', '10.35.61.215', '10.35.37.65', '10.35.57.35', '10.35.57.142', '10.35.55.180', '10.35.49.46', '10.35.58.150', '10.35.33.234', '10.35.34.152', '10.35.33.6', '10.35.42.248', '10.35.37.234', '10.35.35.217', '10.35.58.181', '10.35.62.113', '10.35.37.57', '10.35.33.82', '10.35.48.245', '10.35.62.185', '10.35.58.180', '10.35.54.114', '10.35.56.77', '10.35.43.41', '10.35.38.56', '10.35.40.112', '10.35.32.142', '10.35.46.236', '10.35.42.227', '10.35.55.216', '10.35.55.94', '10.35.47.214', '10.35.59.186', '10.35.61.72', '10.35.40.66', '10.35.48.210', '10.35.61.213', '10.35.41.186', '10.35.52.55', '10.35.59.232', '10.35.56.104', '10.35.58.160', '10.35.37.135', '10.35.45.80', '10.35.63.66', '10.35.40.48', '10.35.48.54', '10.35.47.94', '10.35.40.173', '10.35.52.12', '10.35.39.229', '10.35.59.76', '10.35.42.116', '10.35.56.8', '10.35.57.49', '10.35.48.125', '10.35.62.232', '10.35.54.103', '10.35.49.240', '10.35.58.124', '10.35.61.235', '10.35.61.128', '10.35.55.250', '10.35.52.145', '10.35.39.26', '10.35.34.73', '10.35.57.171', '10.35.54.158', '10.35.53.126', '10.35.54.116', '10.35.59.71', '10.35.46.230', '10.35.47.188', '10.35.48.96', '10.35.45.104', '10.35.54.235', '10.35.48.98', '10.35.37.116', '10.35.46.77', '10.35.43.87', '10.35.40.72', '10.35.48.60', '10.35.54.174', '10.35.37.158', '10.35.44.114', '10.35.41.103', '10.35.43.158', '10.35.46.49', '10.35.49.65', '10.35.33.233', '10.35.44.220', '10.35.33.43', '10.35.32.4', '10.35.50.155', '10.35.51.103', '10.35.34.254', '10.35.51.113', '10.35.36.241', '10.35.59.142', '10.35.56.149', '10.35.46.137', '10.35.42.141', '10.35.42.105', '10.35.48.61', '10.35.51.64', '10.35.52.133', '10.35.50.240', '10.35.35.39', '10.35.37.236', '10.35.49.152', '10.35.45.136', '10.35.57.154', '10.35.36.124', '10.35.48.92', '10.35.62.98', '10.35.34.63', '10.35.45.99', '10.35.45.135', '10.35.44.228', '10.35.41.165', '10.35.60.38', '10.35.32.6', '10.35.32.121', '10.35.60.167', '10.35.62.127', '10.35.32.202', '10.35.39.199', '10.35.61.130', '10.35.47.193', '10.35.36.37', '10.35.44.36', '10.35.45.255', '10.35.62.209', '10.35.37.61', '10.35.32.164', '10.35.58.80', '10.35.60.10', '10.35.54.151', '10.35.47.165', '10.35.52.254', '10.35.43.67', '10.35.60.43', '10.35.42.63', '10.35.55.77', '10.35.60.57', '10.35.56.201', '10.35.32.237', '10.35.43.84', '10.35.52.150', '10.35.45.30', '10.35.36.223', '10.35.55.110', '10.35.53.129', '10.35.60.8', '10.35.51.177', '10.35.62.191', '10.35.58.120', '10.35.48.53', '10.35.34.127', '10.35.49.193', '10.35.62.4', '10.35.59.135', '10.35.43.240', '10.35.59.127', '10.35.33.243', '10.35.50.109', '10.35.60.143', '10.35.54.209', '10.35.34.87', '10.35.42.23', '10.35.53.187', '10.35.46.183', '10.35.32.65', '10.35.40.70', '10.35.36.159', '10.35.52.160', '10.35.50.161', '10.35.52.28', '10.35.42.200', '10.35.45.194', '10.35.62.148', '10.35.44.65', '10.35.39.166', '10.35.50.153', '10.35.36.26', '10.35.36.55', '10.35.43.98', '10.35.61.92', '10.35.51.36', '10.35.39.250', '10.35.40.104', '10.35.42.172', '10.35.41.175', '10.35.47.238', '10.35.39.41', '10.35.43.150', '10.35.44.219', '10.35.40.148', '10.35.62.0', '10.35.46.122', '10.35.62.142', '10.35.61.38', '10.35.38.55', '10.35.55.236', '10.35.42.53', '10.35.42.118', '10.35.52.178', '10.35.54.64', '10.35.63.142', '10.35.42.217', '10.35.49.137', '10.35.32.176', '10.35.35.79', '10.35.53.228', '10.35.36.132', '10.35.40.91', '10.35.40.60', '10.35.50.131', '10.35.55.189', '10.35.61.120', '10.35.44.31', '10.35.62.162', '10.35.33.52', '10.35.38.87', '10.35.44.206', '10.35.34.229', '10.35.48.48', '10.35.42.182', '10.35.62.140', '10.35.57.112', '10.35.57.62', '10.35.53.217', '10.35.52.100', '10.35.50.141', '10.35.56.134', '10.35.53.86', '10.35.36.101', '10.35.46.37', '10.35.43.46', '10.35.43.156', '10.35.32.133', '10.35.34.22', '10.35.41.49', '10.35.45.66', '10.35.33.42', '10.35.60.196', '10.35.58.87', '10.35.62.198', '10.35.61.222', '10.35.57.117', '10.35.37.140', '10.35.40.195', '10.35.55.205', '10.35.55.16', '10.35.49.52', '10.35.40.81', '10.35.43.129', '10.35.48.23', '10.35.32.30', '10.35.50.231', '10.35.54.152', '10.35.37.243', '10.35.40.108', '10.35.49.198', '10.35.58.182', '10.35.47.33', '10.35.51.84', '10.35.55.193', '10.35.61.179', '10.35.52.216', '10.35.33.13', '10.35.50.62', '10.35.56.185', '10.35.47.138', '10.35.63.208', '10.35.49.119', '10.35.41.251', '10.35.48.243', '10.35.34.71', '10.35.38.224', '10.35.57.42', '10.35.35.37', '10.35.40.200', '10.35.57.195', '10.35.36.191', '10.35.43.168', '10.35.61.170', '10.35.38.13', '10.35.49.47', '10.35.60.188', '10.35.43.34', '10.35.45.110', '10.35.35.61', '10.35.39.138', '10.35.62.94', '10.35.37.105', '10.35.34.77', '10.35.53.241', '10.35.32.54', '10.35.63.9', '10.35.55.168', '10.35.37.220', '10.35.37.78', '10.35.62.72', '10.35.54.7', '10.35.32.128', '10.35.57.191', '10.35.59.33', '10.35.37.157', '10.35.63.16', '10.35.50.65', '10.35.54.214', '10.35.39.254', '10.35.39.159', '10.35.35.22', '10.35.36.27', '10.35.35.151', '10.35.44.42', '10.35.47.13', '10.35.45.48', '10.35.60.106', '10.35.49.111', '10.35.60.100', '10.35.45.238', '10.35.41.118', '10.35.60.181', '10.35.38.208', '10.35.38.8', '10.35.50.9', '10.35.46.155', '10.35.39.251', '10.35.44.192', '10.35.60.82', '10.35.42.193', '10.35.60.64', '10.35.48.132', '10.35.55.19', '10.35.43.171', '10.35.38.48', '10.35.39.243', '10.35.47.220', '10.35.60.114', '10.35.53.49', '10.35.33.46', '10.35.50.132', '10.35.59.126', '10.35.43.206', '10.35.53.150', '10.35.36.118', '10.35.47.192', '10.35.42.67', '10.35.42.237', '10.35.60.185', '10.35.44.235', '10.35.32.172', '10.35.48.177', '10.35.54.52', '10.35.37.71', '10.35.41.87', '10.35.60.79', '10.35.56.172', '10.35.43.81', '10.35.33.245', '10.35.43.109', '10.35.51.152', '10.35.55.241', '10.35.43.3', '10.35.60.135', '10.35.41.100', '10.35.41.197', '10.35.52.66', '10.35.39.25', '10.35.60.224', '10.35.36.198', '10.35.57.228', '10.35.55.204', '10.35.62.2', '10.35.38.85', '10.35.40.157', '10.35.34.126', '10.35.46.202', '10.35.56.116', '10.35.53.242', '10.35.48.108', '10.35.41.62', '10.35.40.44', '10.35.60.2', '10.35.35.129', '10.35.62.11', '10.35.46.158', '10.35.45.13', '10.35.46.27', '10.35.47.155', '10.35.50.89', '10.35.52.61', '10.35.53.204', '10.35.61.148', '10.35.42.93', '10.35.47.180', '10.35.62.172', '10.35.39.6', '10.35.60.5', '10.35.51.240', '10.35.52.241', '10.35.45.153', '10.35.53.96', '10.35.36.175', '10.35.36.182', '10.35.40.231', '10.35.37.251', '10.35.36.221', '10.35.33.78', '10.35.32.1', '10.35.63.224', '10.35.39.216', '10.35.33.250', '10.35.48.100', '10.35.37.87', '10.35.37.212', '10.35.49.120', '10.35.53.124', '10.35.41.81', '10.35.59.178', '10.35.42.196', '10.35.51.133', '10.35.41.60', '10.35.63.250', '10.35.45.46', '10.35.57.84', '10.35.47.65', '10.35.55.117', '10.35.57.198', '10.35.58.122', '10.35.35.86', '10.35.48.38', '10.35.37.163', '10.35.47.18', '10.35.32.204', '10.35.42.99', '10.35.57.174', '10.35.54.245', '10.35.61.206', '10.35.37.63', '10.35.62.15', '10.35.63.204', '10.35.59.35', '10.35.40.203', '10.35.44.93', '10.35.43.185', '10.35.48.69', '10.35.58.31', '10.35.51.138', '10.35.34.253', '10.35.53.109', '10.35.32.26', '10.35.62.80', '10.35.54.146', '10.35.50.79', '10.35.36.203', '10.35.59.198', '10.35.49.221', '10.35.47.132', '10.35.59.233', '10.35.48.0', '10.35.62.163', '10.35.33.166', '10.35.34.228', '10.35.57.231', '10.35.43.102', '10.35.43.159', '10.35.54.15', '10.35.55.245', '10.35.57.73', '10.35.43.222', '10.35.49.45', '10.35.40.99', '10.35.63.35', '10.35.60.103', '10.35.46.172', '10.35.34.223', '10.35.34.4', '10.35.46.206', '10.35.54.32', '10.35.58.213', '10.35.35.221', '10.35.49.114', '10.35.40.228', '10.35.56.200', '10.35.61.93', '10.35.41.156', '10.35.50.181', '10.35.47.107', '10.35.35.41', '10.35.45.45', '10.35.57.156', '10.35.53.26', '10.35.41.32', '10.35.45.123', '10.35.47.254', '10.35.52.120', '10.35.34.205', '10.35.55.71', '10.35.33.24', '10.35.41.232', '10.35.59.153', '10.35.46.177', '10.35.43.37', '10.35.39.170', '10.35.52.228', '10.35.42.129', '10.35.49.77', '10.35.39.107', '10.35.63.245', '10.35.36.16', '10.35.61.134', '10.35.42.66', '10.35.39.222', '10.35.52.58', '10.35.32.247', '10.35.40.20', '10.35.41.238', '10.35.59.170', '10.35.59.88', '10.35.46.161', '10.35.49.173', '10.35.41.71', '10.35.61.76', '10.35.39.125', '10.35.47.231', '10.35.35.206', '10.35.51.40', '10.35.60.69', '10.35.36.77', '10.35.51.174', '10.35.58.220', '10.35.48.128', '10.35.36.100', '10.35.34.171', '10.35.62.211', '10.35.63.237', '10.35.34.162', '10.35.47.81', '10.35.34.55', '10.35.41.33', '10.35.63.185', '10.35.47.177', '10.35.58.48', '10.35.52.170', '10.35.51.229', '10.35.37.199', '10.35.50.11', '10.35.61.167', '10.35.41.178', '10.35.61.64', '10.35.43.121', '10.35.39.38', '10.35.33.111', '10.35.34.49', '10.35.33.81', '10.35.49.95', '10.35.38.70', '10.35.43.66', '10.35.38.177', '10.35.42.6', '10.35.37.103', '10.35.54.159', '10.35.47.161', '10.35.43.26', '10.35.38.194', '10.35.49.107', '10.35.61.41', '10.35.62.120', '10.35.48.148', '10.35.42.121', '10.35.48.173', '10.35.45.147', '10.35.63.44', '10.35.52.177', '10.35.59.96', '10.35.41.97', '10.35.58.38', '10.35.57.165', '10.35.49.103', '10.35.62.208', '10.35.54.124', '10.35.40.111', '10.35.33.84', '10.35.38.46', '10.35.39.30', '10.35.52.78', '10.35.57.100', '10.35.63.20', '10.35.42.139', '10.35.47.181', '10.35.58.169', '10.35.40.103', '10.35.50.217', '10.35.50.40', '10.35.61.232', '10.35.52.68', '10.35.37.201', '10.35.56.142', '10.35.43.236', '10.35.63.60', '10.35.62.71', '10.35.52.173', '10.35.60.108', '10.35.43.151', '10.35.56.158', '10.35.46.71', '10.35.61.195', '10.35.36.13', '10.35.56.197', '10.35.55.156', '10.35.43.39', '10.35.40.247', '10.35.48.139', '10.35.37.231', '10.35.38.112', '10.35.51.23', '10.35.53.211', '10.35.32.166', '10.35.56.108', '10.35.33.119', '10.35.44.184', '10.35.34.27', '10.35.32.147', '10.35.32.81', '10.35.33.33', '10.35.39.209', '10.35.51.26', '10.35.36.117', '10.35.60.253', '10.35.36.208', '10.35.48.161', '10.35.34.125', '10.35.54.12', '10.35.51.162', '10.35.58.243', '10.35.54.143', '10.35.57.136', '10.35.51.150', '10.35.36.107', '10.35.38.72', '10.35.54.34', '10.35.49.112', '10.35.52.125', '10.35.46.181', '10.35.57.12', '10.35.48.120', '10.35.34.7', '10.35.43.214', '10.35.55.200', '10.35.41.106', '10.35.38.31', '10.35.58.1', '10.35.35.102', '10.35.36.244', '10.35.60.42', '10.35.58.56', '10.35.48.152', '10.35.45.246', '10.35.39.104', '10.35.46.255', '10.35.37.151', '10.35.55.111', '10.35.40.255', '10.35.63.71', '10.35.40.123', '10.35.47.34', '10.35.52.59', '10.35.44.166', '10.35.57.34', '10.35.36.161', '10.35.32.74', '10.35.45.33', '10.35.56.156', '10.35.57.132', '10.35.35.163', '10.35.45.176', '10.35.41.138', '10.35.52.201', '10.35.63.214', '10.35.61.200', '10.35.44.153', '10.35.61.131', '10.35.37.50', '10.35.32.97', '10.35.48.129', '10.35.45.196', '10.35.56.252', '10.35.60.176', '10.35.35.198', '10.35.62.16', '10.35.49.115', '10.35.44.100', '10.35.62.29', '10.35.39.154', '10.35.33.167', '10.35.42.130', '10.35.53.253', '10.35.55.26', '10.35.60.195', '10.35.51.201', '10.35.55.42', '10.35.44.140', '10.35.56.250', '10.35.54.88', '10.35.54.248', '10.35.40.158', '10.35.52.181', '10.35.63.41', '10.35.47.5', '10.35.52.14', '10.35.62.95', '10.35.36.20', '10.35.48.138', '10.35.44.252', '10.35.47.201', '10.35.52.156', '10.35.38.203', '10.35.32.19', '10.35.38.101', '10.35.52.31', '10.35.33.251', '10.35.46.117', '10.35.57.186', '10.35.52.231', '10.35.44.141', '10.35.59.38', '10.35.49.40', '10.35.35.255', '10.35.51.213', '10.35.34.180', '10.35.56.0', '10.35.52.30', '10.35.32.248', '10.35.55.44', '10.35.50.145', '10.35.43.194', '10.35.61.152', '10.35.36.201', '10.35.33.178', '10.35.58.228', '10.35.62.131', '10.35.57.118', '10.35.53.214', '10.35.41.73', '10.35.34.109', '10.35.57.220', '10.35.43.137', '10.35.34.135', '10.35.55.46', '10.35.57.69', '10.35.45.126', '10.35.49.37', '10.35.38.148', '10.35.58.14', '10.35.32.87', '10.35.45.115', '10.35.38.82', '10.35.52.245', '10.35.47.242', '10.35.40.161', '10.35.43.200', '10.35.51.89', '10.35.33.132', '10.35.57.166', '10.35.38.65', '10.35.42.28', '10.35.32.160', '10.35.57.134', '10.35.41.3', '10.35.42.57', '10.35.54.246', '10.35.38.16', '10.35.44.137', '10.35.46.124', '10.35.61.11', '10.35.58.221', '10.35.37.245', '10.35.55.127', '10.35.61.18', '10.35.54.160', '10.35.58.223', '10.35.35.54', '10.35.49.8', '10.35.61.129', '10.35.33.7', '10.35.61.35', '10.35.56.13', '10.35.50.144', '10.35.43.187', '10.35.51.43', '10.35.48.84', '10.35.51.111', '10.35.51.35', '10.35.62.197', '10.35.40.232', '10.35.60.130', '10.35.49.27', '10.35.45.253', '10.35.33.147', '10.35.51.196', '10.35.58.157', '10.35.32.231', '10.35.55.69', '10.35.48.232', '10.35.61.52', '10.35.39.7', '10.35.33.187', '10.35.33.149', '10.35.58.62', '10.35.54.220', '10.35.38.4', '10.35.43.243', '10.35.44.121', '10.35.61.13', '10.35.33.57', '10.35.60.126', '10.35.62.238', '10.35.63.47', '10.35.47.39', '10.35.45.59', '10.35.42.55', '10.35.55.149', '10.35.58.4', '10.35.54.89', '10.35.40.145', '10.35.34.75', '10.35.62.39', '10.35.53.237', '10.35.37.96', '10.35.35.152', '10.35.36.225', '10.35.62.58', '10.35.33.189', '10.35.54.130', '10.35.56.67', '10.35.33.157', '10.35.41.76', '10.35.60.179', '10.35.61.212', '10.35.61.90', '10.35.55.151', '10.35.45.49', '10.35.38.80', '10.35.61.153', '10.35.50.63', '10.35.60.95', '10.35.47.253', '10.35.62.81', '10.35.32.195', '10.35.47.46', '10.35.46.61', '10.35.46.171', '10.35.47.234', '10.35.49.200', '10.35.53.171', '10.35.56.182', '10.35.59.116', '10.35.62.75', '10.35.43.83', '10.35.51.44', '10.35.63.195', '10.35.48.190', '10.35.51.247', '10.35.48.199', '10.35.59.238', '10.35.35.76', '10.35.41.24', '10.35.35.84', '10.35.38.253', '10.35.54.13', '10.35.43.233', '10.35.56.4', '10.35.44.107', '10.35.44.54', '10.35.32.177', '10.35.53.98', '10.35.32.254', '10.35.62.69', '10.35.48.16', '10.35.44.18', '10.35.38.114', '10.35.43.219', '10.35.52.42', '10.35.47.168', '10.35.63.248', '10.35.56.83', '10.35.56.167', '10.35.59.217', '10.35.46.234', '10.35.32.243', '10.35.48.233', '10.35.61.127', '10.35.42.30', '10.35.53.63', '10.35.36.238', '10.35.55.85', '10.35.35.29', '10.35.51.30', '10.35.58.59', '10.35.48.144', '10.35.35.183', '10.35.42.76', '10.35.58.20', '10.35.46.219', '10.35.36.7', '10.35.60.140', '10.35.36.147', '10.35.41.153', '10.35.47.44', '10.35.58.9', '10.35.58.102', '10.35.59.117', '10.35.43.125', '10.35.32.194', '10.35.39.158', '10.35.37.17', '10.35.40.253', '10.35.57.124', '10.35.50.57', '10.35.40.252', '10.35.54.2', '10.35.55.235', '10.35.58.34', '10.35.33.51', '10.35.54.119', '10.35.33.160', '10.35.59.216', '10.35.57.235', '10.35.33.158', '10.35.50.108', '10.35.55.41', '10.35.43.146', '10.35.45.20', '10.35.34.51', '10.35.46.203', '10.35.63.177', '10.35.36.28', '10.35.51.236', '10.35.37.47', '10.35.57.239', '10.35.62.237', '10.35.56.159', '10.35.32.40', '10.35.59.160', '10.35.32.24', '10.35.60.201', '10.35.54.62', '10.35.48.182', '10.35.58.156', '10.35.58.161', '10.35.62.223', '10.35.60.175', '10.35.44.208', '10.35.61.2', '10.35.60.61', '10.35.35.18', '10.35.52.2', '10.35.62.244', '10.35.46.81', '10.35.32.187', '10.35.46.69', '10.35.48.105', '10.35.33.100', '10.35.58.109', '10.35.51.91', '10.35.47.198', '10.35.55.226', '10.35.52.217', '10.35.62.10', '10.35.49.220', '10.35.37.175', '10.35.43.196', '10.35.37.68', '10.35.45.200', '10.35.34.16', '10.35.38.100', '10.35.33.101', '10.35.61.201', '10.35.46.14', '10.35.35.231', '10.35.41.150', '10.35.43.32', '10.35.56.186', '10.35.48.97', '10.35.55.140', '10.35.32.171', '10.35.51.252', '10.35.39.74', '10.35.56.68', '10.35.40.167', '10.35.32.170', '10.35.48.208', '10.35.60.65', '10.35.39.246', '10.35.57.212', '10.35.43.62', '10.35.56.95', '10.35.44.159', '10.35.61.188', '10.35.57.226', '10.35.34.58', '10.35.46.94', '10.35.52.112', '10.35.51.185', '10.35.51.209', '10.35.39.118', '10.35.32.53', '10.35.36.99', '10.35.63.94', '10.35.62.141', '10.35.55.107', '10.35.39.224', '10.35.60.234', '10.35.35.207', '10.35.3

In [37]:
all_phase_ips = phase1_ips | phase2_ips | phase3_ips | phase4_ips
print(len(all_phase_ips), "unique IPs across all phases.")

for i, ip in enumerate(all_phase_ips):
    in_phases = []
    if ip in phase1_ips:
        in_phases.append("Phase 1")
    if ip in phase2_ips:
        in_phases.append("Phase 2")
    if ip in phase3_ips:
        in_phases.append("Phase 3")
    if ip in phase4_ips:
        in_phases.append("Phase 4")
    
    if len(in_phases) > 1:
        print(f"IP {ip} appears in: {', '.join(in_phases)}")

8209 unique IPs across all phases.
IP 10.35.35.206 appears in: Phase 2, Phase 3, Phase 4
IP 172.17.130.37 appears in: Phase 2, Phase 4
IP 192.168.255.254 appears in: Phase 1, Phase 4
IP 192.168.128.4 appears in: Phase 2, Phase 4
IP 172.17.130.196 appears in: Phase 2, Phase 3, Phase 4
IP 192.168.130.77 appears in: Phase 1, Phase 2, Phase 4