# Analyze DARPA 2000 Attack Phases

In [1]:
import pandas as pd

## Load Attack Data

In [2]:
dataset = "darpa2000"
scenario = "s1_dmz"
data_dir = f"../data/interim/{dataset}/{scenario}/flows_unlabeled"

In [3]:
dfs = []

attack_phases = list(range(1, 6)) 
for phase in attack_phases:
    print(f"Phase: {phase}")

    df = pd.read_csv(
        f"{data_dir}/phase{phase}_flows.csv"
    )

    dfs.append(df)

Phase: 1
Phase: 2
Phase: 3
Phase: 4
Phase: 5

In [4]:
def analyze_phase(df, print_details=True):

    src_ips = df["src_ip"].value_counts()
    dst_ips = df["dst_ip"].value_counts()
    src_ports = df["sport"].value_counts()
    dst_ports = df["dport"].value_counts()

    if print_details:
        print("Total Flows:", len(df))

        print("\n --- IP distribution ---")
        print(f"\nSource IPs ({len(src_ips)}):")
        print(src_ips)
        print(f"\nDestination IPs ({len(dst_ips)}):")
        print(dst_ips)

        print("\n --- Port distribution ---")
        print(f"Source Ports ({len(src_ports)}):")
        print(src_ports)
        print(f"\nDestination Ports ({len(dst_ports)}):")
        print(dst_ports)

    return src_ips, dst_ips, src_ports, dst_ports

## Phase 1: IP Sweep

In [5]:
df_1 = dfs[0]
df_1

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.254,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
1,f1,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.252,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
2,f2,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.250,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
3,f3,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.247,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
4,f4,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.246,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,f762,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.19,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
763,f763,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.21,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
764,f764,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.113.203,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
765,f765,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.25,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
766,f766,9.524407e+08,9.524407e+08,0.0,202.77.162.213,8,172.16.112.26,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1

In [6]:
src_ips_1, dst_ips_1, src_ports_1, dst_ports_1 = analyze_phase(df_1)

Total Flows: 767

 --- IP distribution ---

Source IPs (1):
src_ip
202.77.162.213    767
Name: count, dtype: int64

Destination IPs (767):
dst_ip
172.16.112.26     1
172.16.112.254    1
172.16.112.252    1
172.16.112.250    1
172.16.112.247    1
                 ..
172.16.112.217    1
172.16.112.226    1
172.16.112.227    1
172.16.112.228    1
172.16.112.229    1
Name: count, Length: 767, dtype: int64

 --- Port distribution ---
Source Ports (1):
sport
8    767
Name: count, dtype: int64

Destination Ports (1):
dport
0    767
Name: count, dtype: int64

## Phase 2: Sadmind Ping

In [7]:
df_2 = dfs[1]
df_2

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524416e+08,9.524417e+08,55.104582,202.77.162.213,645,172.16.115.1,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
1,f1,9.524417e+08,9.524417e+08,0.006824,202.77.162.213,646,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
2,f2,9.524417e+08,9.524417e+08,0.121852,202.77.162.213,647,172.16.115.20,54791,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
3,f3,9.524417e+08,9.524417e+08,55.110270,202.77.162.213,647,172.16.115.87,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
4,f4,9.524418e+08,9.524419e+08,55.101701,202.77.162.213,649,172.16.114.2,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
5,f5,9.524419e+08,9.524419e+08,0.002622,202.77.162.213,650,172.16.114.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
6,f6,9.524419e+08,9.524419e+08,0.471611,202.77.162.213,651,172.16.114.10,32779,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
7,f7,9.524419e+08,9.524419e+08,0.001940,202.77.162.213,651,172.16.114.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
8,f8,9.524419e+08,9.524419e+08,0.568888,202.77.162.213,652,172.16.114.20,32773,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
9,f9,9.524419e+08,9.524419e+08,0.001891,202.77.162.213,652,172.16.114.30,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
10,f10,9.524419e+08,9.524419e+08,0.550163,202.77.162.213,653,172.16.114.30,32772,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
11,f11,9.524419e+08,9.524419e+08,0.000000,202.77.162.213,653,172.16.114.50,111,udp,-,...,F,T,0,D,1,84,0,0,-,17
12,f12,9.524419e+08,9.524419e+08,0.000000,172.16.114.50,3,202.77.162.213,3,icmp,-,...,T,F,0,-,1,112,0,0,-,1
13,f13,9.524419e+08,9.524419e+08,55.107404,202.77.162.213,654,172.16.113.1,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
14,f14,9.524419e+08,9.524419e+08,0.007893,202.77.162.213,655,172.16.113.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
15,f15,9.524419e+08,9.524420e+08,55.104407,202.77.162.213,656,172.16.113.105,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
16,f16,9.524420e+08,9.524420e+08,55.101990,202.77.162.213,657,172.16.113.148,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
17,f17,9.524420e+08,9.524421e+08,55.101717,202.77.162.213,658,172.16.112.1,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
18,f18,9.524421e+08,9.524421e+08,0.010345,202.77.162.213,659,172.16.112.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
19,f19,9.524421e+08,9.524421e+08,0.058064,202.77.162.213,660,172.16.112.10,56255,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
20,f20,9.524421e+08,9.524421e+08,0.006791,202.77.162.213,660,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
21,f21,9.524421e+08,9.524421e+08,0.085522,202.77.162.213,661,172.16.112.50,56261,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
22,f22,9.524421e+08,9.524422e+08,55.109268,202.77.162.213,661,172.16.112.100,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
23,f23,9.524422e+08,9.524422e+08,55.101789,202.77.162.213,662,172.16.112.105,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
24,f24,9.524422e+08,9.524423e+08,55.101779,202.77.162.213,663,172.16.112.194,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17

In [8]:
src_ips_2, dst_ips_2, src_ports_2, dst_ports_2 = analyze_phase(df_2)

Total Flows: 25

 --- IP distribution ---

Source IPs (2):
src_ip
202.77.162.213    24
172.16.114.50      1
Name: count, dtype: int64

Destination IPs (19):
dst_ip
172.16.115.20     2
172.16.114.20     2
172.16.114.10     2
172.16.112.50     2
172.16.112.10     2
172.16.114.30     2
172.16.115.1      1
172.16.115.87     1
202.77.162.213    1
172.16.114.50     1
172.16.114.2      1
172.16.113.50     1
172.16.113.1      1
172.16.113.148    1
172.16.113.105    1
172.16.112.1      1
172.16.112.100    1
172.16.112.105    1
172.16.112.194    1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (19):
sport
647    2
651    2
652    2
660    2
661    2
653    2
645    1
646    1
3      1
649    1
650    1
655    1
654    1
656    1
657    1
659    1
658    1
662    1
663    1
Name: count, dtype: int64

Destination Ports (8):
dport
111      18
54791     1
32779     1
32773     1
32772     1
3         1
56255     1
56261     1
Name: count, dtype: int64

In [9]:
different_dst_ips = dst_ips_1.index.difference(dst_ips_2.index)
different_dst_ips

Index(['172.16.112.101', '172.16.112.102', '172.16.112.103', '172.16.112.104',
       '172.16.112.106', '172.16.112.107', '172.16.112.108', '172.16.112.109',
       '172.16.112.11', '172.16.112.110',
       ...
       '172.16.115.90', '172.16.115.91', '172.16.115.92', '172.16.115.93',
       '172.16.115.94', '172.16.115.95', '172.16.115.96', '172.16.115.97',
       '172.16.115.98', '172.16.115.99'],
      dtype='object', name='dst_ip', length=749)

In [10]:
# Check which homenet IPs are involved in each phase
common_dst_ips = dst_ips_1.index.intersection(dst_ips_2.index)
common_dst_ips

Index(['172.16.112.194', '172.16.112.100', '172.16.112.105', '172.16.112.50',
       '172.16.112.10', '172.16.114.2', '172.16.114.20', '172.16.115.20',
       '172.16.113.105', '172.16.115.87', '172.16.114.10', '172.16.115.1',
       '172.16.112.1', '172.16.114.50', '172.16.114.30', '172.16.113.1',
       '172.16.113.50', '172.16.113.148'],
      dtype='object', name='dst_ip')

In [11]:
active_ips = dst_ips_1.index.intersection(src_ips_2.index)
active_ips

Index(['172.16.114.50'], dtype='object')

## Phase 3: Exploiting

In [12]:
df_3 = dfs[2]
df_3

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524432e+08,9.524432e+08,8.269662,202.77.162.213,1425,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaFf,13,566,13,639,-,6
1,f1,9.524432e+08,9.524432e+08,8.309972,202.77.162.213,1488,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaFf,13,566,13,639,-,6
2,f2,9.524432e+08,9.524432e+08,1.595575,202.77.162.213,1495,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaFf,13,566,13,679,-,6
3,f3,9.524432e+08,9.524432e+08,4.256986,202.77.162.213,1496,172.16.114.10,23,tcp,-,...,F,T,0,ShAdDaFf,14,606,14,679,-,6
4,f4,9.524432e+08,9.524432e+08,4.222506,202.77.162.213,1497,172.16.114.10,23,tcp,-,...,F,T,0,ShAdDaFf,13,566,13,639,-,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,f75,9.524433e+08,9.524433e+08,0.004114,202.77.162.213,685,172.16.114.30,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
76,f76,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,699,172.16.112.50,60618,udp,-,...,F,T,0,D,1,1440,0,0,-,17
77,f77,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,690,172.16.114.30,32772,udp,-,...,F,T,0,D,1,1440,0,0,-,17
78,f78,9.524433e+08,9.524433e+08,0.007011,202.77.162.213,697,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
79,f79,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,685,172.16.114.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17

In [13]:
src_ips_3, dst_ips_3, src_ports_3, dst_ports_3 = analyze_phase(df_3)

Total Flows: 80

 --- IP distribution ---

Source IPs (1):
src_ip
202.77.162.213    80
Name: count, dtype: int64

Destination IPs (6):
dst_ip
172.16.115.20    15
172.16.114.10    15
172.16.114.20    15
172.16.114.30    15
172.16.112.10    10
172.16.112.50    10
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (49):
sport
668     2
671     2
672     2
670     2
673     2
669     2
683     2
682     2
698     2
681     2
680     2
679     2
678     2
677     2
676     2
675     2
674     2
686     2
688     2
695     2
687     2
685     2
692     2
690     2
689     2
684     2
694     2
696     2
691     2
693     2
697     2
1425    1
1496    1
1506    1
1505    1
1504    1
1495    1
1497    1
1498    1
1503    1
667     1
1488    1
1534    1
1531    1
1532    1
1507    1
1533    1
1535    1
699     1
Name: count, dtype: int64

Destination Ports (19):
dport
111      32
23       16
32773     6
32772     6
32779     6
60250     1
60254     1
60288     1
60275     1
60299     1
60268     1
60577     1
60604     1
60541     1
60518     1
60548     1
60523     1
60568     1
60618     1
Name: count, dtype: int64

## Phase 4: Installation

In [14]:
df_4 = dfs[3]
df_4

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524442e+08,9.524442e+08,0.178301,172.16.115.20,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,6,346,7,336,-,6
1,f1,9.524442e+08,9.524442e+08,1.228680,172.16.115.20,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,24,1055,39,45765,-,6
2,f2,9.524442e+08,9.524442e+08,1.106557,172.16.115.20,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,6,346,7,336,-,6
3,f3,9.524442e+08,9.524442e+08,0.002247,202.77.162.213,1535,172.16.112.50,23,tcp,-,...,F,T,0,FafA,2,80,2,80,-,6
4,f4,9.524442e+08,9.524442e+08,1.247215,172.16.115.20,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,29,1255,49,61337,-,6
5,f5,9.524442e+08,9.524442e+08,1.173117,202.77.162.213,1023,172.16.115.20,514,tcp,-,...,F,T,0,ShADadFf,7,327,6,245,-,6
6,f6,9.524442e+08,9.524442e+08,0.170003,172.16.112.10,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,6,346,7,336,-,6
7,f7,9.524442e+08,9.524442e+08,0.150988,202.77.162.213,1021,172.16.115.20,514,tcp,-,...,F,T,0,ShADadFf,6,301,5,205,-,6
8,f8,9.524442e+08,9.524442e+08,1.269908,172.16.112.10,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,25,1095,39,45765,-,6
9,f9,9.524442e+08,9.524442e+08,0.170562,172.16.112.50,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,6,346,7,336,-,6
10,f10,9.524442e+08,9.524442e+08,0.112376,202.77.162.213,1019,172.16.112.10,514,tcp,-,...,F,T,0,ShADadFf,6,301,5,205,-,6
11,f11,9.524442e+08,9.524442e+08,0.321156,172.16.112.50,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,25,1095,39,45765,-,6
12,f12,9.524443e+08,9.524443e+08,0.001377,172.16.112.50,1023,202.77.162.213,1016,tcp,-,...,T,F,0,ShA,2,100,1,44,-,6
13,f13,9.524443e+08,9.524443e+08,0.118438,202.77.162.213,1017,172.16.112.50,514,tcp,-,...,F,T,0,ShADadFf,6,301,5,205,-,6
14,f14,9.524442e+08,9.524442e+08,1.006902,202.77.162.213,1565,172.16.112.50,23,tcp,-,...,F,T,0,ShAdDf,23,1141,23,2459,-,6
15,f15,9.524442e+08,9.524442e+08,0.001307,172.16.115.20,1022,202.77.162.213,1020,tcp,-,...,T,F,0,ShA,2,100,1,44,-,6
16,f16,9.524442e+08,9.524442e+08,0.001277,172.16.112.10,1023,202.77.162.213,1018,tcp,-,...,T,F,0,ShA,2,100,1,44,-,6
17,f17,9.524442e+08,9.524442e+08,0.001292,172.16.115.20,1023,202.77.162.213,1022,tcp,-,...,T,F,0,ShA,2,100,1,44,-,6
18,f18,9.524442e+08,9.524442e+08,1.824443,202.77.162.213,1537,172.16.112.10,23,tcp,-,...,F,T,0,ShAdDf,23,1141,23,1347,-,6
19,f19,9.524442e+08,9.524442e+08,4.260213,202.77.162.213,1536,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaf,27,1404,28,1626,-,6

In [15]:
src_ips_4, dst_ips_4, src_ports_4, dst_ports_4 = analyze_phase(df_4)

Total Flows: 20

 --- IP distribution ---

Source IPs (4):
src_ip
202.77.162.213    8
172.16.115.20     6
172.16.112.10     3
172.16.112.50     3
Name: count, dtype: int64

Destination IPs (4):
dst_ip
202.77.162.213    12
172.16.112.50      3
172.16.115.20      3
172.16.112.10      2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (9):
sport
1023    12
1535     1
1021     1
1019     1
1017     1
1565     1
1022     1
1537     1
1536     1
Name: count, dtype: int64

Destination Ports (6):
dport
514     12
23       4
1016     1
1020     1
1018     1
1022     1
Name: count, dtype: int64

## Phase 5: Launching DDoS

In [16]:
df_5 = dfs[4]
df_5

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524464e+08,9.524464e+08,0.001545,172.16.115.20,1022,202.77.162.213,1020,tcp,-,...,T,F,0,FafA,2,80,2,80,-,6
1,f1,9.524465e+08,9.524465e+08,0.000000,131.84.1.31,4047,8.138.161.2,4939,tcp,-,...,F,F,0,R,1,40,0,0,-,6
2,f2,9.524465e+08,9.524465e+08,0.000000,131.84.1.31,31938,61.56.80.155,4940,tcp,-,...,F,F,0,R,1,40,0,0,-,6
3,f3,9.524465e+08,9.524465e+08,0.000000,131.84.1.31,6439,116.107.159.190,4941,tcp,-,...,F,F,0,R,1,40,0,0,-,6
4,f4,9.524465e+08,9.524465e+08,0.000000,131.84.1.31,24037,45.4.65.127,4942,tcp,-,...,F,F,0,R,1,40,0,0,-,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33937,f33937,9.524473e+08,9.524473e+08,0.073494,172.16.115.5,49779,131.84.1.31,80,tcp,http,...,T,F,0,ShADadfF,10,732,19,21877,-,6
33938,f33938,9.524473e+08,9.524473e+08,0.048319,172.16.115.5,49778,131.84.1.31,80,tcp,http,...,T,F,0,ShADadfF,7,597,9,6530,-,6
33939,f33939,9.524473e+08,9.524473e+08,0.025293,172.16.115.5,49777,131.84.1.31,80,tcp,http,...,T,F,0,ShADdfFa,5,527,5,2472,-,6
33940,f33940,9.524473e+08,9.524473e+08,0.036301,172.16.115.5,49776,131.84.1.31,80,tcp,http,...,T,F,0,ShADdfFa,6,517,6,4445,-,6
33941,f33941,9.524464e+08,9.524469e+08,485.693936,202.77.162.213,1566,172.16.115.20,23,tcp,-,...,F,T,0,ShADadt,305,12519,176,8664,-,6

In [17]:
proto_counts = df_5["proto"].value_counts()
print("Protocol distribution in Phase 5:")
print(proto_counts)

Protocol distribution in Phase 5:
proto
tcp    33942
Name: count, dtype: int64

In [18]:
src_ips_5, dst_ips_5, src_ports_5, dst_ports_5 = analyze_phase(df_5)

Total Flows: 33942

 --- IP distribution ---

Source IPs (56):
src_ip
131.84.1.31        33858
172.16.115.5          22
172.16.116.201         9
172.16.115.20          1
53.253.36.19           1
91.47.196.195          1
112.26.251.196         1
111.17.135.149         1
97.147.189.211         1
4.219.227.108          1
115.52.150.164         1
57.7.232.146           1
61.164.243.98          1
7.217.114.68           1
74.16.179.12           1
29.162.78.184          1
94.165.225.71          1
17.12.183.91           1
105.102.88.0           1
56.97.150.156          1
106.104.12.137         1
1.68.52.136            1
97.223.199.124         1
3.118.198.0            1
120.42.177.54          1
122.173.22.113         1
56.239.162.55          1
75.60.227.51           1
103.88.93.247          1
27.22.106.169          1
102.80.167.66          1
70.200.150.65          1
109.246.18.188         1
76.72.133.143          1
20.208.22.244          1
93.178.63.97           1
100.3.198.110          1
76.195.107.15          1
13.210.0.204           1
10.38.119.244          1
35.153.116.103         1
110.133.133.148        1
2.70.7.212             1
60.255.143.87          1
69.142.195.112         1
40.253.151.46          1
100.53.236.24          1
99.222.228.202         1
12.185.28.115          1
0.175.44.129           1
50.134.149.106         1
93.87.185.69           1
56.189.53.233          1
15.74.4.116            1
78.114.221.56          1
202.77.162.213         1
Name: count, dtype: int64

Destination IPs (33861):
dst_ip
131.84.1.31        82
66.242.208.131      1
80.155.50.113       1
119.248.196.222     1
98.170.83.151       1
                   ..
49.225.73.255       1
4.29.219.65         1
2.148.16.165        1
18.23.101.56        1
110.173.139.2       1
Name: count, Length: 33861, dtype: int64

 --- Port distribution ---
Source Ports (21185):
sport
13863    8
5953     7
30161    7
7184     7
855      6
        ..
49778    1
49779    1
49780    1
49781    1
49782    1
Name: count, Length: 21185, dtype: int64

Destination Ports (33887):
dport
80       33
143       4
53        4
81        3
8080      3
         ..
16337     1
16338     1
16339     1
16340     1
16332     1
Name: count, Length: 33887, dtype: int64

In [19]:
counter = 0
for ip in df_5["dst_ip"]:
    if ip.startswith("172.16."):
        counter += 1
print(f"Number of destination IPs in phase 5 that are in the homenet: {counter}")

Number of destination IPs in phase 5 that are in the homenet: 1